version: '3'
services:
  db_service:
    image: postgres
    container_name: db_service
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db_service
